version: "2"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVER_NAME=kibana
      - I18N_LOCALE="zh-CN"
      - ELASTICSEARCH_HOSTS=http://172.16.16.134:9200
    # mem_limit: ${MEM_LIMIT}