version: '3'

services:
  mysql8:
    image: 'mysql:oracle'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      # - :/etc/mysql/conf.d
      - /Users/zhangxs/DockerVolumes/mysql8/data:/var/lib/mysql
    ports:
      - 3306:3306