version: '3'

services:
  mysql8:
    image: 'mysql:8-debian'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      # - :/etc/mysql/conf.d
      - ~/docker-volumes/mysql8/data:/var/lib/mysql
    ports:
      - 3306:3306