version: "3"

services:
  redis:
    image: 'redis:${REDIS_VERSION}'
    volumes:
      - ${REDIS_CONFIG}:/etc/redis/redis.conf
      - ${REDIS_DATA}:/data
    ports:
      - '6379:6379'
    command: redis-server /etc/redis/redis.conf